apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://REPLACE_WITH_TOMORROWS_RDS_ENDPOINT:5432/shopflow"
  ORDER_EVENTS_QUEUE_NAME: "shopflow-order-events"
  AWS_REGION: "us-east-1"
